/**
 * Authoritative list of free, self-built EdTools.
 * Source of truth for /edtools and /edtools/[slug] routes.
 * Pulled from https://github.com/alfredang/AI-LMS-TMS README.
 *
 * Only self-built tools are listed (alfredang.github.io / *.streamlit.app / *.vercel.app) —
 * third-party platforms referenced in the README (ChatGPT, HeyGen, n8n, Zoom, …) are excluded.
 *
 * `repo` is the alfredang/<repo> name. For GitHub Pages tools it equals the live-URL path
 * segment, so the detail page can build a valid github.com link. For streamlit/vercel-hosted
 * tools the repo is uncertain, so it is left unset and the GitHub button is hidden.
 *
 * Live screenshots live in R2 — see src/lib/edtools-screenshots.ts (generated by
 * scripts/upload-edtools-screenshots.ts) and getEdToolScreenshot().
 */

import type { IconType } from "react-icons";
import {
  HiOutlineUsers,
  HiOutlineClipboardDocumentList,
  HiOutlinePuzzlePiece,
  HiOutlineShieldCheck,
  HiOutlineBanknotes,
  HiOutlineUserGroup,
  HiOutlineChartBar,
  HiOutlineCpuChip,
  HiOutlineChartPie,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineSignal,
  HiOutlineCube,
  HiOutlineSparkles,
  HiOutlinePaintBrush,
} from "react-icons/hi2";
import { EDTOOL_SCREENSHOTS } from "./edtools-screenshots";

export type EdTool = {
  slug: string;
  name: string;
  category: EdToolCategory;
  description: string;
  /** Optional alfredang/<repo> name — used to link to live demo + GitHub. */
  repo?: string;
  /** Live demo URL if a deployed instance exists. */
  demoUrl?: string;
  /** Optional list of features rendered as bullets on the detail page. */
  features?: string[];
  /** Suggested tech-stack chips for the detail page. */
  stack?: string[];
};

export const ED_TOOL_CATEGORIES = [
  "Interactive Classroom",
  "Project Management",
  "Problem Solving",
  "Cyber Security",
  "Finance",
  "HR & Interview",
  "Data Analytics",
  "Machine Learning",
  "Statistics & SPC",
  "Sustainability",
  "Networking",
  "Blockchain",
  "Quantum",
  "Design",
] as const;
export type EdToolCategory = (typeof ED_TOOL_CATEGORIES)[number];

/** Per-category presentation metadata for the index cards. */
export const CATEGORY_META: Record<EdToolCategory, { icon: IconType; accent: string; blurb: string }> = {
  "Interactive Classroom": {
    icon: HiOutlineUsers,
    accent: "#59EBFD",
    blurb: "Live classroom widgets — polls, boards, timers, and Q&A that learners join from a single link.",
  },
  "Project Management": {
    icon: HiOutlineClipboardDocumentList,
    accent: "#7C5CFF",
    blurb: "Facilitation canvases for RACI, Agile, Design Thinking, and Business Model Canvas exercises.",
  },
  "Problem Solving": {
    icon: HiOutlinePuzzlePiece,
    accent: "#59EBFD",
    blurb: "Root-cause and structured-thinking frameworks — 5 Whys, Fishbone, Pareto, and causal loops.",
  },
  "Cyber Security": {
    icon: HiOutlineShieldCheck,
    accent: "#FF6B6B",
    blurb: "Browser-based attack-and-defence labs and crypto tooling — safe, sandboxed, zero setup.",
  },
  Finance: {
    icon: HiOutlineBanknotes,
    accent: "#34D399",
    blurb: "Singapore tax, FP&A, ratio analysis, trend analysis, and credit-risk calculators.",
  },
  "HR & Interview": {
    icon: HiOutlineUserGroup,
    accent: "#7C5CFF",
    blurb: "Personality assessment and AI-assisted interview practice and question generation.",
  },
  "Data Analytics": {
    icon: HiOutlineChartBar,
    accent: "#59EBFD",
    blurb: "Pivot exploration, anomaly detection, factor analysis, and synthetic-data generation.",
  },
  "Machine Learning": {
    icon: HiOutlineCpuChip,
    accent: "#FBBF24",
    blurb: "Train and evaluate classification and clustering models straight in the browser.",
  },
  "Statistics & SPC": {
    icon: HiOutlineChartPie,
    accent: "#59EBFD",
    blurb: "Statistics, Design of Experiments, and Statistical Process Control workbenches.",
  },
  Sustainability: {
    icon: HiOutlineGlobeAsiaAustralia,
    accent: "#34D399",
    blurb: "Singapore-aligned carbon-emissions tracking for organisations.",
  },
  Networking: {
    icon: HiOutlineSignal,
    accent: "#7C5CFF",
    blurb: "Subnetting, packet analysis, and regex building for networking and IT training.",
  },
  Blockchain: {
    icon: HiOutlineCube,
    accent: "#FBBF24",
    blurb: "On-chain certificate issuance, supply-chain verification, and hashing utilities.",
  },
  Quantum: {
    icon: HiOutlineSparkles,
    accent: "#7C5CFF",
    blurb: "Browser-based quantum-algorithm simulation for introductory quantum-computing classes.",
  },
  Design: {
    icon: HiOutlinePaintBrush,
    accent: "#FF6B6B",
    blurb: "Lightweight creative tooling for class branding and asset creation.",
  },
};

export const EDTOOLS: EdTool[] = [
  // ── Interactive Classroom ─────────────────────────────────────────────
  {
    slug: "ice-breaker",
    name: "Ice Breaker",
    category: "Interactive Classroom",
    description: "Engaging icebreaker activities to warm up a class — quick games, prompts, and pair-shares for new cohorts.",
    repo: "ice-breaker",
    demoUrl: "https://alfredang.github.io/ice-breaker/",
    stack: ["JavaScript", "HTML5", "Real-time"],
    features: [
      "Quick prompts for new cohorts and corporate workshops",
      "Random pair / small-group generator",
      "Single-link join — no learner accounts required",
    ],
  },
  {
    slug: "pinboard",
    name: "Pinboard",
    category: "Interactive Classroom",
    description: "Padlet-style sticky-note canvas for collaborative brainstorming, retrospectives, and idea capture.",
    repo: "pinboard",
    demoUrl: "https://alfredang.github.io/pinboard/",
    stack: ["React", "Real-time", "Drag & drop"],
    features: [
      "Drag-and-drop sticky notes with colour grouping",
      "Real-time multi-user collaboration",
      "Export the board as image / JSON",
    ],
  },
  {
    slug: "break-timer",
    name: "Break Timer",
    category: "Interactive Classroom",
    description: "Musical countdown timer for class breaks — keeps the room in sync, brings everyone back on time.",
    repo: "musical-timer-countdown",
    demoUrl: "https://alfredang.github.io/musical-timer-countdown/",
    stack: ["JavaScript", "Web Audio API"],
    features: [
      "Visual countdown with configurable break length",
      "Background music playlist that fades on resume",
      "Full-screen presenter mode",
    ],
  },
  {
    slug: "word-cloud",
    name: "Word Cloud",
    category: "Interactive Classroom",
    description: "Live word-cloud generator — learners contribute words on their phones and watch the cloud grow on the projector.",
    repo: "wordcloud",
    demoUrl: "https://alfredang.github.io/wordcloud/",
    stack: ["JavaScript", "Canvas", "WebSocket"],
    features: [
      "Live updates as learners submit",
      "Stopword filtering + size weighting",
      "Export PNG/SVG for reports",
    ],
  },
  {
    slug: "flash-cards",
    name: "Flash Cards",
    category: "Interactive Classroom",
    description: "Digital flashcard system with spaced repetition for vocabulary, terminology, and certification prep.",
    repo: "flashcard",
    demoUrl: "https://alfredang.github.io/flashcard/",
    stack: ["React", "LocalStorage", "Spaced repetition"],
    features: [
      "Spaced-repetition review queue",
      "Import flashcards from CSV / spreadsheet",
      "Per-deck progress tracking",
    ],
  },
  {
    slug: "live-qa",
    name: "Live Q&A",
    category: "Interactive Classroom",
    description: "Real-time audience Q&A — learners submit questions and upvote others, trainer answers in priority order.",
    repo: "live-qna",
    demoUrl: "https://alfredang.github.io/live-qna/",
    stack: ["React", "Firebase", "Real-time"],
    features: [
      "Audience upvoting surfaces the best questions",
      "Anonymous mode for sensitive topics",
      "Mark-as-answered + export Q&A log",
    ],
  },
  {
    slug: "whiteboard",
    name: "Whiteboard",
    category: "Interactive Classroom",
    description: "Digital whiteboard for live instruction — drawing, shapes, text, real-time multi-user collaboration.",
    repo: "whiteboard",
    demoUrl: "https://alfredang.github.io/whiteboard/",
    stack: ["Canvas", "WebSocket", "Real-time"],
    features: [
      "Free-hand drawing + shape tools",
      "Multi-user simultaneous editing",
      "Export to PNG / PDF",
    ],
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    category: "Interactive Classroom",
    description: "Generate QR codes on the fly for class activities — link to polls, resources, attendance, or join URLs.",
    repo: "qrcodegenerator",
    demoUrl: "https://alfredang.github.io/qrcodegenerator/",
    stack: ["JavaScript", "Canvas"],
    features: [
      "Instant QR for any URL or text",
      "Download as PNG / SVG",
      "Project full-screen for the room to scan",
    ],
  },
  {
    slug: "padlet",
    name: "Padlet",
    category: "Interactive Classroom",
    description: "Wall-style collaborative posting space for class discussion, resource sharing, and group exhibits.",
    repo: "padlet",
    demoUrl: "https://alfredang.github.io/padlet/",
    stack: ["React", "Real-time", "Media uploads"],
    features: [
      "Sticky-note style posts with image + link attachments",
      "Trainer moderation controls",
      "Export the wall as PDF for assessment",
    ],
  },
  {
    slug: "collaborative-note",
    name: "Collaborative Note",
    category: "Interactive Classroom",
    description: "Shared note-taking workspace — multiple learners write the same document, trainer sees everyone in real time.",
    repo: "collabnote",
    demoUrl: "https://alfredang.github.io/collabnote/",
    stack: ["React", "Yjs / CRDT", "WebSocket"],
    features: [
      "Real-time concurrent editing (CRDT-based)",
      "Per-learner cursor and colour tag",
      "Export to Markdown / DOCX",
    ],
  },
  {
    slug: "collaborative-flow",
    name: "Collaborative Flow",
    category: "Interactive Classroom",
    description: "Process flow diagramming tool for groups — drag-and-drop nodes and connectors, ideal for SOP mapping exercises.",
    repo: "collabflow",
    demoUrl: "https://alfredang.github.io/collabflow/",
    stack: ["React", "React Flow", "Real-time"],
    features: [
      "Library of flowchart primitives",
      "Multi-user editing of the same diagram",
      "Export to SVG / PNG",
    ],
  },
  {
    slug: "collaborative-kanban",
    name: "Collaborative Kanban",
    category: "Interactive Classroom",
    description: "Board-based task management for group projects — drag cards across columns in real time.",
    repo: "kanban",
    demoUrl: "https://alfredang.github.io/kanban/",
    stack: ["React", "Real-time", "Drag & drop"],
    features: [
      "Configurable columns (Todo / Doing / Done by default)",
      "Card assignment + colour labels",
      "Multi-user real-time updates",
    ],
  },
  {
    slug: "live-poll",
    name: "Live Poll",
    category: "Interactive Classroom",
    description: "Real-time audience polling with bar-chart results — drop a link, learners vote, results animate live.",
    repo: "livepoll",
    demoUrl: "https://alfredang.github.io/livepoll/",
    stack: ["React", "Firebase", "Real-time"],
    features: [
      "Single-choice, multi-choice, and ranking modes",
      "Anonymous voting",
      "Export results to CSV",
    ],
  },
  {
    slug: "mindmaps",
    name: "Mind Maps",
    category: "Interactive Classroom",
    description: "Branching mind-map editor for brainstorming and curriculum planning.",
    repo: "mindmapping",
    demoUrl: "https://alfredang.github.io/mindmapping/",
    stack: ["React", "SVG", "Real-time"],
    features: [
      "Drag-to-add child nodes",
      "Colour-coded branches",
      "Export to PNG / PDF / Markdown outline",
    ],
  },
  {
    slug: "spinning-wheel",
    name: "Spinning Wheel",
    category: "Interactive Classroom",
    description: "Random-selection wheel for cold-calling, fair allocation, or gamified breaks.",
    repo: "spinning-wheel",
    demoUrl: "https://alfredang.github.io/spinning-wheel/",
    stack: ["JavaScript", "Canvas", "Web Audio"],
    features: [
      "Custom labels with weighted probability",
      "Sound + confetti on selection",
      "Mark-as-used so picks are non-repeating",
    ],
  },

  // ── Project Management ────────────────────────────────────────────────
  {
    slug: "raci-matrix",
    name: "RACI Matrix",
    category: "Project Management",
    description: "Responsible / Accountable / Consulted / Informed mapping tool for clarifying roles on any project or process.",
    repo: "raci",
    demoUrl: "https://alfredang.github.io/raci/",
    stack: ["JavaScript", "HTML5"],
    features: [
      "Build the RACI grid task-by-task",
      "Validation warnings (e.g. more than one 'A')",
      "Export the matrix to CSV / image",
    ],
  },
  {
    slug: "digital-transformation",
    name: "Digital / AI Transformation",
    category: "Project Management",
    description: "Assessment-and-planning canvas for digital and AI transformation — score maturity and plan the roadmap.",
    repo: "digitaltransformation",
    demoUrl: "https://alfredang.github.io/digitaltransformation/",
    stack: ["JavaScript", "HTML5"],
    features: [
      "Maturity self-assessment across dimensions",
      "Gap-to-target visualisation",
      "Prioritised roadmap output",
    ],
  },
  {
    slug: "agile-scrum",
    name: "Agile / Scrum",
    category: "Project Management",
    description: "Sprint planning and tracking framework for teaching Agile ceremonies and the Scrum workflow.",
    repo: "scrum",
    demoUrl: "https://alfredang.github.io/scrum/",
    stack: ["JavaScript", "HTML5"],
    features: [
      "Backlog → sprint board flow",
      "Burndown visualisation",
      "Role and ceremony walkthrough",
    ],
  },
  {
    slug: "design-thinking",
    name: "Design Thinking Studio",
    category: "Project Management",
    description: "Problem-solving toolkit that walks groups through the five design-thinking stages — empathise to test.",
    repo: "designthinking",
    demoUrl: "https://alfredang.github.io/designthinking/",
    stack: ["JavaScript", "HTML5"],
    features: [
      "Stage-by-stage facilitation canvas",
      "Persona and empathy-map templates",
      "Idea capture and dot-voting",
    ],
  },
  {
    slug: "bmc-studio",
    name: "BMC Studio",
    category: "Project Management",
    description: "Business Model Canvas builder — fill the nine blocks collaboratively for startup and strategy exercises.",
    repo: "bcm",
    demoUrl: "https://alfredang.github.io/bcm/",
    stack: ["JavaScript", "HTML5"],
    features: [
      "Nine-block canvas with sticky notes",
      "Multiple saved canvases",
      "Export to image / PDF",
    ],
  },

  // ── Problem Solving ───────────────────────────────────────────────────
  {
    slug: "five-whys",
    name: "5 Whys",
    category: "Problem Solving",
    description: "Root-cause analysis framework — drill from symptom to systemic cause in five linked questions.",
    repo: "5whys",
    demoUrl: "https://alfredang.github.io/5whys/",
    stack: ["JavaScript", "Print-ready export"],
    features: [
      "Structured 5-Whys form",
      "Save / share analysis sessions",
      "Export the chain as PDF",
    ],
  },
  {
    slug: "fishbone-diagram",
    name: "Fishbone Diagram",
    category: "Problem Solving",
    description: "Ishikawa cause-and-effect diagram editor — categorise root causes across People / Process / Tech / Environment.",
    repo: "fishbone",
    demoUrl: "https://alfredang.github.io/fishbone/",
    stack: ["JavaScript", "SVG"],
    features: [
      "Customisable cause categories",
      "Drag-and-drop bones and sub-causes",
      "Export PNG / SVG / PDF",
    ],
  },
  {
    slug: "pareto-chart",
    name: "Pareto Chart",
    category: "Problem Solving",
    description: "ABC / 80-20 analysis visualiser — paste in counts, get the cumulative-% Pareto chart instantly.",
    repo: "paretochart",
    demoUrl: "https://alfredang.github.io/paretochart/",
    stack: ["JavaScript", "Charting"],
    features: [
      "Paste-in or CSV-upload input",
      "Cumulative % overlay + 80% guide line",
      "Export chart + ranked table",
    ],
  },
  {
    slug: "system-thinking",
    name: "System Thinking",
    category: "Problem Solving",
    description: "Causal-loop diagram editor for systems thinking — model reinforcing and balancing loops.",
    repo: "systemloop",
    demoUrl: "https://alfredang.github.io/systemloop/",
    stack: ["JavaScript", "SVG"],
    features: [
      "Reinforcing + balancing loop notation",
      "Snapshot loops for facilitation",
      "Export to PNG / PDF",
    ],
  },

  // ── Cyber Security ────────────────────────────────────────────────────
  {
    slug: "cyberlabs",
    name: "Cyber Labs",
    category: "Cyber Security",
    description: "Browser-based cybersecurity simulation environment — run attack-and-defence scenarios safely in a sandbox.",
    repo: "cybersecuritysimulator",
    demoUrl: "https://alfredang.github.io/cybersecuritysimulator/",
    stack: ["JavaScript", "Browser sandbox"],
    features: [
      "Common attack-and-defence scenarios",
      "No setup — runs entirely in the browser",
      "Trainer view of learner attempts",
    ],
  },
  {
    slug: "hacklabs",
    name: "Ethical Hacking Labs",
    category: "Cyber Security",
    description: "Ethical hacking practical-exercises lab — scenario-based exercises for hands-on red-team training.",
    repo: "ethnicalhacking",
    demoUrl: "https://alfredang.github.io/ethnicalhacking/",
    stack: ["JavaScript", "Browser sandbox"],
    features: [
      "Scenario-based ethical-hacking exercises",
      "Step-by-step guided attack flow",
      "Browser-only — zero risk to real systems",
    ],
  },
  {
    slug: "pentest-fauxbank",
    name: "Pentest Labs (FauxBank)",
    category: "Cyber Security",
    description: "Banking cybersecurity pentest lab — a fictional bank with realistic vulnerabilities for safe practitioner training.",
    demoUrl: "https://pentest-fauxbank.vercel.app/",
    stack: ["Next.js", "Vercel", "Realistic vulns"],
    features: [
      "Realistic banking web app with known vulns",
      "Walk-through guides + free-form mode",
      "Safe, isolated environment",
    ],
  },
  {
    slug: "cryptography",
    name: "Cryptography Toolkit",
    category: "Cyber Security",
    description: "Encryption and hashing toolkit — classical ciphers, symmetric/asymmetric encryption, and hash functions.",
    repo: "cryptography-toolkit",
    demoUrl: "https://alfredang.github.io/cryptography-toolkit/",
    stack: ["JavaScript", "Web Crypto API"],
    features: [
      "Classical ciphers + modern encryption demos",
      "Hashing across common algorithms",
      "Step-by-step explanations for teaching",
    ],
  },

  // ── Finance ───────────────────────────────────────────────────────────
  {
    slug: "tax-calculator",
    name: "Tax Calculator",
    category: "Finance",
    description: "Singapore tax computation — personal and corporate brackets with deductions and reliefs.",
    repo: "novataxsg",
    demoUrl: "https://alfredang.github.io/novataxsg/",
    stack: ["JavaScript", "SG tax brackets"],
    features: [
      "Singapore brackets + reliefs",
      "Side-by-side scenario comparison",
      "Shareable computation",
    ],
  },
  {
    slug: "financial-planning-analysis",
    name: "Financial Planning & Analysis",
    category: "Finance",
    description: "Lightweight FP&A modelling — budgets, forecasts, variance, and scenarios.",
    repo: "novafinance",
    demoUrl: "https://alfredang.github.io/novafinance/",
    stack: ["JavaScript", "Charting"],
    features: [
      "Roll-up budgets across cost centres",
      "Driver-based forecasting",
      "Variance reporting",
    ],
  },
  {
    slug: "financial-ratio-calculators",
    name: "Financial Ratio Calculators",
    category: "Finance",
    description: "Compute liquidity, profitability, leverage, and efficiency ratios from a P&L + balance sheet.",
    repo: "novafinancialratiocalculator",
    demoUrl: "https://alfredang.github.io/novafinancialratiocalculator/",
    stack: ["JavaScript", "SG SFRS"],
    features: [
      "Standard ratio set (current, quick, debt-to-equity, ROA, ROE…)",
      "Year-on-year comparison",
      "Plain-language interpretation",
    ],
  },
  {
    slug: "financial-trend-analysis",
    name: "Financial Trend Analysis",
    category: "Finance",
    description: "Upload financial statements (CSV/Excel), surface trends, ratios, and anomalies in one click.",
    repo: "financialtrend",
    demoUrl: "https://alfredang.github.io/financialtrend/",
    stack: ["JavaScript", "Browser-only"],
    features: [
      "Zero-build, runs entirely client-side",
      "Trend + ratio + anomaly views",
      "Demo dataset included",
    ],
  },
  {
    slug: "credit-loan-analysis",
    name: "Credit Loan Analysis",
    category: "Finance",
    description: "Per-loan Expected Loss, Lifetime ECL, and portfolio risk indicators for retail/SME lending.",
    demoUrl: "https://creditloananalysis.streamlit.app/",
    stack: ["Streamlit", "Pandas"],
    features: [
      "Per-loan EL / LGD / PD",
      "Lifetime ECL roll-forward",
      "Portfolio concentration warnings",
    ],
  },

  // ── HR & Interview ────────────────────────────────────────────────────
  {
    slug: "mbti",
    name: "MBTI Assessment",
    category: "HR & Interview",
    description: "Personality-type assessment — answer the questionnaire and get a 16-type profile with descriptions.",
    repo: "mbti",
    demoUrl: "https://alfredang.github.io/mbti/#landing",
    stack: ["JavaScript", "HTML5"],
    features: [
      "Full questionnaire flow",
      "16-type result with strengths/blind-spots",
      "Shareable result page",
    ],
  },
  {
    slug: "ai-interview-coach",
    name: "AI Interview Coach",
    category: "HR & Interview",
    description: "Conversational interview-preparation coach — practise answers and get structured feedback.",
    repo: "ai-interviewing",
    demoUrl: "https://alfredang.github.io/ai-interviewing/",
    stack: ["JavaScript", "LLM"],
    features: [
      "Role-specific mock interviews",
      "Structured feedback on answers",
      "Practise at your own pace",
    ],
  },
  {
    slug: "hr-interview-gen",
    name: "HR Interview Generator",
    category: "HR & Interview",
    description: "Generate role-tailored interview questions for HR teams and hiring managers in seconds.",
    repo: "hr-interviewing",
    demoUrl: "https://alfredang.github.io/hr-interviewing/",
    stack: ["JavaScript", "LLM"],
    features: [
      "Questions tailored to role + seniority",
      "Behavioural and technical sets",
      "Copy / export the question bank",
    ],
  },

  // ── Data Analytics ────────────────────────────────────────────────────
  {
    slug: "pivot-visualization",
    name: "Pivot Visualization",
    category: "Data Analytics",
    description: "Upload a CSV, build pivot tables in the browser, and chart aggregates — no Excel needed.",
    repo: "novapivot",
    demoUrl: "https://alfredang.github.io/novapivot/",
    stack: ["JavaScript", "Browser-only"],
    features: [
      "Drag-and-drop dimensions + measures",
      "Chart on top of the pivot",
      "Export pivot + chart",
    ],
  },
  {
    slug: "anomaly-detection",
    name: "Anomaly Detection",
    category: "Data Analytics",
    description: "Statistical anomaly identifier for operational data — flag outliers and visualise them in one UI.",
    repo: "anamolydetection2",
    demoUrl: "https://alfredang.github.io/anamolydetection2/",
    stack: ["JavaScript", "Browser-only"],
    features: [
      "Multiple detection methods",
      "Tunable thresholds",
      "Annotated chart of flagged points",
    ],
  },
  {
    slug: "factor-analysis",
    name: "Factor Analysis",
    category: "Data Analytics",
    description: "Multifactor statistical analysis tool — eigenvalues, scree plot, loadings, and rotation.",
    demoUrl: "https://multifactoranalysis.streamlit.app/",
    stack: ["Streamlit", "Pandas", "FactorAnalyzer"],
    features: [
      "Upload CSV + select variables",
      "Bartlett / KMO sphericity tests",
      "Varimax / oblimin rotation options",
    ],
  },
  {
    slug: "mock-data-generator",
    name: "Mock Data Generator",
    category: "Data Analytics",
    description: "Generate realistic test datasets — names, addresses, financial figures, time series — straight to CSV.",
    repo: "mockdatagen",
    demoUrl: "https://alfredang.github.io/mockdatagen/",
    stack: ["JavaScript", "Faker"],
    features: [
      "Pick schema from templates or build custom",
      "Locale-aware profiles",
      "Download as CSV / JSON",
    ],
  },

  // ── Machine Learning ──────────────────────────────────────────────────
  {
    slug: "ml-classification",
    name: "ML Classification",
    category: "Machine Learning",
    description: "Train and evaluate supervised classification models in the browser — upload data, compare algorithms.",
    demoUrl: "https://ml-classification-888.streamlit.app/",
    stack: ["Streamlit", "scikit-learn", "Pandas"],
    features: [
      "Side-by-side model comparison",
      "Confusion matrix + ROC curve",
      "Feature-importance view",
    ],
  },
  {
    slug: "ml-clustering",
    name: "ML Clustering",
    category: "Machine Learning",
    description: "Unsupervised pattern discovery — K-means and friends with cluster visualisation and metrics.",
    demoUrl: "https://mlclustering-888.streamlit.app/",
    stack: ["Streamlit", "scikit-learn", "Pandas"],
    features: [
      "Choose algorithm + cluster count",
      "Silhouette and elbow diagnostics",
      "2-D cluster scatter plot",
    ],
  },

  // ── Statistics & SPC ──────────────────────────────────────────────────
  {
    slug: "novastats",
    name: "NovaStats",
    category: "Statistics & SPC",
    description: "Probability, descriptive, correlation, regression, hypothesis, confidence-interval, and Bayesian inference in one browser tool.",
    repo: "novastats",
    demoUrl: "https://alfredang.github.io/novastats/",
    stack: ["JavaScript", "Browser-only"],
    features: [
      "Multiple statistical workflows in one UI",
      "Paste-in data — no upload needed",
      "Plain-language interpretation alongside output",
    ],
  },
  {
    slug: "novadoe",
    name: "NovaDOE",
    category: "Statistics & SPC",
    description: "Design of Experiments suite — full + fractional factorial, Taguchi, central composite, Box-Behnken, Plackett-Burman, Latin square, response surface.",
    repo: "novadoe",
    demoUrl: "https://alfredang.github.io/novadoe/",
    stack: ["JavaScript", "Browser-only"],
    features: [
      "Eight DOE methodologies",
      "Auto-generated run sheet",
      "Response-surface contour plotting",
    ],
  },
  {
    slug: "novaspc",
    name: "NovaSPC",
    category: "Statistics & SPC",
    description: "Statistical Process Control — c, u, np, p, X-mR, X̄-R, X̄-s control charts plus capability and distribution analysis.",
    repo: "novaspc",
    demoUrl: "https://alfredang.github.io/novaspc/",
    stack: ["JavaScript", "Browser-only"],
    features: [
      "Seven control-chart types",
      "Process capability (Cp, Cpk, Pp, Ppk)",
      "Distribution-fit testing",
    ],
  },

  // ── Sustainability ────────────────────────────────────────────────────
  {
    slug: "carbon-footprint-calculator",
    name: "Carbon Footprint Calculator",
    category: "Sustainability",
    description: "Singapore-specific carbon-emissions tracker for organisations — Scope 1, 2, and select Scope 3 categories.",
    repo: "sgcarboncalculator",
    demoUrl: "https://alfredang.github.io/sgcarboncalculator/",
    stack: ["JavaScript", "SG grid factors"],
    features: [
      "Singapore-aligned emission factors",
      "Scope 1 / 2 / 3 (partial) input",
      "Export a GHG report",
    ],
  },

  // ── Networking ────────────────────────────────────────────────────────
  {
    slug: "ip-calculator",
    name: "IP Calculator",
    category: "Networking",
    description: "Subnet and CIDR calculator — work out network, broadcast, host range, and mask from any address.",
    repo: "ipcalculator",
    demoUrl: "https://alfredang.github.io/ipcalculator/",
    stack: ["JavaScript", "HTML5"],
    features: [
      "CIDR ↔ subnet-mask conversion",
      "Network / broadcast / host-range output",
      "Subnetting practice mode",
    ],
  },
  {
    slug: "pcap-analyzer",
    name: "PCAP Analyzer",
    category: "Networking",
    description: "Browser-based network packet-capture analyser — inspect protocols and flows from a PCAP file.",
    repo: "pcapanalyzer",
    demoUrl: "https://alfredang.github.io/pcapanalyzer/",
    stack: ["JavaScript", "Browser-only"],
    features: [
      "Parse PCAP entirely in the browser",
      "Protocol + conversation breakdown",
      "Filter and drill into packets",
    ],
  },
  {
    slug: "regex-generator",
    name: "Regex Generator",
    category: "Networking",
    description: "Build and test regular expressions interactively with live match highlighting and explanations.",
    repo: "regexgenerator",
    demoUrl: "https://alfredang.github.io/regexgenerator/",
    stack: ["JavaScript", "HTML5"],
    features: [
      "Live match highlighting",
      "Pattern explanation breakdown",
      "Common-pattern presets",
    ],
  },

  // ── Blockchain ────────────────────────────────────────────────────────
  {
    slug: "certify-nft",
    name: "Certify NFT",
    category: "Blockchain",
    description: "Issue tamper-proof course certificates as NFTs — anchored on-chain and instantly verifiable.",
    repo: "certifynft",
    demoUrl: "https://alfredang.github.io/certifynft/",
    stack: ["Solidity", "Ethereum", "Web3"],
    features: [
      "Issue certificates on-chain",
      "Public verification page",
      "Tamper-evident records",
    ],
  },
  {
    slug: "supply-verify",
    name: "Supply Verify",
    category: "Blockchain",
    description: "Blockchain-anchored supply-chain product identification — provenance, custody, and authenticity in one ledger.",
    repo: "supplyverify",
    demoUrl: "https://alfredang.github.io/supplyverify/",
    stack: ["Solidity", "Ethereum"],
    features: [
      "Mint product identifiers on-chain",
      "Chain-of-custody event log",
      "Consumer-facing verification page",
    ],
  },
  {
    slug: "hashing-tool",
    name: "Hashing Tool",
    category: "Blockchain",
    description: "Cryptographic hash generator — produce and compare hashes across common algorithms for integrity demos.",
    repo: "hashgenerator",
    demoUrl: "https://alfredang.github.io/hashgenerator/",
    stack: ["JavaScript", "Web Crypto API"],
    features: [
      "Hash text or files",
      "Multiple algorithms (SHA family and more)",
      "Compare two hashes for integrity",
    ],
  },

  // ── Quantum ───────────────────────────────────────────────────────────
  {
    slug: "quantum-labs",
    name: "Quantum Labs",
    category: "Quantum",
    description: "Browser-based quantum-algorithm simulator for introducing qubits, gates, and circuits in class.",
    repo: "quantumlabs",
    demoUrl: "https://alfredang.github.io/quantumlabs/",
    stack: ["JavaScript", "Browser-only"],
    features: [
      "Build simple quantum circuits",
      "Visualise qubit states",
      "Run introductory algorithms",
    ],
  },

  // ── Design ────────────────────────────────────────────────────────────
  {
    slug: "logo-maker",
    name: "Logo Maker",
    category: "Design",
    description: "Lightweight graphic logo-creation tool for class branding, team identities, and quick design exercises.",
    repo: "logomaker",
    demoUrl: "https://alfredang.github.io/logomaker/",
    stack: ["JavaScript", "Canvas"],
    features: [
      "Icon + text composition",
      "Colour and font controls",
      "Export as PNG / SVG",
    ],
  },
];

export function getEdToolBySlug(slug: string): EdTool | undefined {
  return EDTOOLS.find((t) => t.slug === slug);
}

export function getEdToolsGrouped(): Record<EdToolCategory, EdTool[]> {
  const out = Object.fromEntries(ED_TOOL_CATEGORIES.map((c) => [c, [] as EdTool[]])) as Record<
    EdToolCategory,
    EdTool[]
  >;
  for (const t of EDTOOLS) out[t.category].push(t);
  return out;
}

/** R2 public URL of the live screenshot for a tool, or undefined if not yet captured. */
export function getEdToolScreenshot(slug: string): string | undefined {
  return EDTOOL_SCREENSHOTS[slug];
}

/** Short noun describing the category, used in SEO copy ("a free <noun> tool"). */
const CATEGORY_NOUN: Record<EdToolCategory, string> = {
  "Interactive Classroom": "interactive classroom",
  "Project Management": "project-management",
  "Problem Solving": "problem-solving",
  "Cyber Security": "cybersecurity training",
  Finance: "finance",
  "HR & Interview": "HR & interview",
  "Data Analytics": "data-analytics",
  "Machine Learning": "machine-learning",
  "Statistics & SPC": "statistics & SPC",
  Sustainability: "sustainability",
  Networking: "networking",
  Blockchain: "blockchain",
  Quantum: "quantum-computing",
  Design: "design",
};

/**
 * SEO metadata for a tool's detail page. Title is kept short because the root
 * layout appends " | Tertiary Infotech Academy" via the title template.
 */
export function getEdToolSeo(tool: EdTool): {
  title: string;
  description: string;
  keywords: string;
} {
  const noun = CATEGORY_NOUN[tool.category];
  const title = `Free ${tool.name} — Online Tool for Trainers & Educators`;
  const description = `${tool.name} is a free, browser-based ${noun} tool by Tertiary Infotech Academy. Open the live demo, view the source on GitHub, or enquire to add it to your own LMS.`;
  const keywords = [
    `free ${tool.name.toLowerCase()}`,
    `${tool.name.toLowerCase()} online`,
    `${tool.name.toLowerCase()} for trainers`,
    `${noun} tool`,
    "free edtech tools Singapore",
    "online teaching tools",
    "LMS Singapore",
  ].join(", ");
  return { title, description, keywords };
}

/** FAQ pairs for a tool — rendered visibly AND mirrored 1:1 into FAQPage JSON-LD. */
export function getEdToolFaqs(tool: EdTool): { q: string; a: string }[] {
  const noun = CATEGORY_NOUN[tool.category];
  const faqs: { q: string; a: string }[] = [
    {
      q: `Is ${tool.name} free to use?`,
      a: `Yes. ${tool.name} is completely free and runs in your browser — there is no signup, licence fee, or trial limit. Tertiary Infotech Academy built it for our own ${noun} sessions and made it openly available to trainers and educators.`,
    },
    {
      q: `Do I need to install anything to use ${tool.name}?`,
      a: `No. ${tool.name} is a browser-based tool — just open the live demo on any modern device. Learners can usually join from a single link with no accounts required.`,
    },
    {
      q: `Can I use ${tool.name} inside my own LMS or training programme?`,
      a: `Yes. We can brand, integrate, and deploy ${tool.name} — or the full suite of ${EDTOOLS.length}+ Ed Tools — inside your own Learning / Training Management System with WSQ/TPQA-compliant workflows. Enquire using the form and a consultant will reply within one business day.`,
    },
  ];
  if (tool.repo) {
    faqs.push({
      q: `Is the source code for ${tool.name} available?`,
      a: `Yes. ${tool.name} is open-source — you can view the code on GitHub at github.com/alfredang/${tool.repo}.`,
    });
  }
  return faqs;
}
